USE [master]
GO

/****** Object:  Database [SummerActivities]    Script Date: 5/19/2024 7:27:31 PM ******/
CREATE DATABASE [SummerActivities]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SummerActivities', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SummerActivities.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SummerActivities_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SummerActivities_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SummerActivities].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SummerActivities] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SummerActivities] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SummerActivities] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SummerActivities] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SummerActivities] SET ARITHABORT OFF 
GO

ALTER DATABASE [SummerActivities] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SummerActivities] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SummerActivities] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SummerActivities] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SummerActivities] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SummerActivities] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SummerActivities] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SummerActivities] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SummerActivities] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SummerActivities] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SummerActivities] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SummerActivities] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SummerActivities] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SummerActivities] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SummerActivities] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SummerActivities] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SummerActivities] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SummerActivities] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SummerActivities] SET  MULTI_USER 
GO

ALTER DATABASE [SummerActivities] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SummerActivities] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SummerActivities] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SummerActivities] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SummerActivities] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SummerActivities] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SummerActivities] SET QUERY_STORE = ON
GO

ALTER DATABASE [SummerActivities] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SummerActivities] SET  READ_WRITE 
GO


